import type { LucideIcon } from "lucide-react";
import {
  CalendarDays,
  CheckSquare,
  Flag,
  FolderKanban,
  Goal,
  Link2,
  Mail,
  NotebookPen,
  Repeat,
  Search,
  Settings,
  Sparkles,
} from "lucide-react";
import type { CreateEntityType } from "@/types";

export type CommandAction =
  | { kind: "create"; type: CreateEntityType }
  | { kind: "navigate"; href: string }
  | { kind: "search" };

export type AppCommand = {
  id: string;
  label: string;
  keywords: string[];
  group: "Ask" | "Create" | "Navigate" | "Search";
  icon: LucideIcon;
  shortcut?: string;
  action: CommandAction;
};

export const appCommands: AppCommand[] = [
  {
    id: "ask-lifeos",
    label: "Ask LifeOS",
    keywords: ["ai", "chat", "assistant", "brain"],
    group: "Ask",
    icon: Sparkles,
    action: { kind: "navigate", href: "/ai" },
  },
  {
    id: "plan-my-day",
    label: "Plan my day",
    keywords: ["ai", "schedule", "today", "focus"],
    group: "Ask",
    icon: Sparkles,
    action: { kind: "navigate", href: "/ai?prompt=Plan%20my%20day" },
  },
  {
    id: "review-my-goals",
    label: "Review my goals",
    keywords: ["ai", "goals", "progress"],
    group: "Ask",
    icon: Sparkles,
    action: { kind: "navigate", href: "/ai?prompt=Review%20my%20goals" },
  },
  {
    id: "summarize-my-week",
    label: "Summarize my week",
    keywords: ["ai", "review", "week"],
    group: "Ask",
    icon: Sparkles,
    action: { kind: "navigate", href: "/ai?prompt=Summarize%20my%20week" },
  },
  {
    id: "open-ai",
    label: "Open AI",
    keywords: ["chat", "assistant", "ask", "lifeos"],
    group: "Ask",
    icon: Sparkles,
    action: { kind: "navigate", href: "/ai" },
  },
  {
    id: "create-task",
    label: "Create task",
    keywords: ["new", "todo", "add"],
    group: "Create",
    icon: CheckSquare,
    action: { kind: "create", type: "task" },
  },
  {
    id: "create-note",
    label: "New note",
    keywords: ["new", "write", "doc", "capture"],
    shortcut: "N",
    group: "Create",
    icon: NotebookPen,
    action: { kind: "create", type: "note" },
  },
  {
    id: "create-goal",
    label: "Create goal",
    keywords: ["new", "target", "objective"],
    group: "Create",
    icon: Goal,
    shortcut: "G",
    action: { kind: "create", type: "goal" },
  },
  {
    id: "create-project",
    label: "Create project",
    keywords: ["new", "workspace"],
    group: "Create",
    icon: FolderKanban,
    shortcut: "P",
    action: { kind: "create", type: "project" },
  },
  {
    id: "create-habit",
    label: "Create habit",
    keywords: ["new", "streak", "daily"],
    group: "Create",
    icon: Repeat,
    action: { kind: "create", type: "habit" },
  },
  {
    id: "create-milestone",
    label: "Create milestone",
    keywords: ["checkpoint", "step", "goal"],
    group: "Create",
    icon: Flag,
    action: { kind: "create", type: "milestone" },
  },
  {
    id: "create-event",
    label: "New event",
    keywords: ["calendar", "schedule", "meeting", "new"],
    group: "Create",
    icon: CalendarDays,
    action: { kind: "create", type: "event" },
  },
  {
    id: "search-everything",
    label: "Search everything",
    keywords: ["find", "lookup", "query"],
    group: "Search",
    icon: Search,
    shortcut: "/",
    action: { kind: "search" },
  },
  {
    id: "search-tasks",
    label: "Search tasks",
    keywords: ["find", "todo", "filter"],
    group: "Search",
    icon: CheckSquare,
    action: { kind: "navigate", href: "/tasks" },
  },
  {
    id: "search-notes",
    label: "Search notes",
    keywords: ["find", "write", "docs"],
    group: "Search",
    icon: NotebookPen,
    action: { kind: "navigate", href: "/notes" },
  },
  {
    id: "search-projects",
    label: "Search projects",
    keywords: ["find", "workspace"],
    group: "Search",
    icon: FolderKanban,
    action: { kind: "navigate", href: "/projects" },
  },
  {
    id: "go-tasks",
    label: "Go to Tasks",
    keywords: ["open", "todo", "list"],
    group: "Navigate",
    icon: CheckSquare,
    action: { kind: "navigate", href: "/tasks" },
  },
  {
    id: "go-projects",
    label: "Go to Projects",
    keywords: ["open", "workspace"],
    group: "Navigate",
    icon: FolderKanban,
    action: { kind: "navigate", href: "/projects" },
  },
  {
    id: "go-goals",
    label: "Go to Goals",
    keywords: ["open", "outcomes"],
    group: "Navigate",
    icon: Goal,
    action: { kind: "navigate", href: "/goals" },
  },
  {
    id: "go-habits",
    label: "Go to Habits",
    keywords: ["open", "streaks", "daily"],
    group: "Navigate",
    icon: Repeat,
    action: { kind: "navigate", href: "/habits" },
  },
  {
    id: "go-notes",
    label: "Go to Notes",
    keywords: ["open", "write", "docs"],
    group: "Navigate",
    icon: NotebookPen,
    action: { kind: "navigate", href: "/notes" },
  },
  {
    id: "open-calendar",
    label: "Open calendar",
    keywords: ["schedule", "events", "date"],
    group: "Navigate",
    icon: CalendarDays,
    action: { kind: "navigate", href: "/calendar" },
  },
  {
    id: "go-settings",
    label: "Go to settings",
    keywords: ["preferences", "theme", "account"],
    group: "Navigate",
    icon: Settings,
    action: { kind: "navigate", href: "/settings" },
  },
  {
    id: "open-integrations",
    label: "Open Integrations",
    keywords: ["connect", "google", "gmail", "github", "oauth", "settings"],
    group: "Navigate",
    icon: Link2,
    action: { kind: "navigate", href: "/settings/integrations" },
  },
  {
    id: "connect-google-calendar",
    label: "Connect Google Calendar",
    keywords: ["oauth", "sync", "schedule", "integration"],
    group: "Navigate",
    icon: CalendarDays,
    action: { kind: "navigate", href: "/api/integrations/google/start?provider=calendar" },
  },
  {
    id: "connect-gmail",
    label: "Connect Gmail",
    keywords: ["oauth", "email", "mail", "integration"],
    group: "Navigate",
    icon: Mail,
    action: { kind: "navigate", href: "/api/integrations/google/start?provider=gmail" },
  },
  {
    id: "connect-github",
    label: "Connect GitHub",
    keywords: ["oauth", "repo", "commits", "integration"],
    group: "Navigate",
    icon: FolderKanban,
    action: { kind: "navigate", href: "/api/integrations/github/start" },
  },
];
